### PR TITLE
Fixing Script version issue

### LINKED ISSUE #2: Undefined constant SCRIPT_VERSION
I get that error:
`Notice: Use of undefined constant SCRIPT_VERSION - assumed 'SCRIPT_VERSION' in /htdocs/wp-content/plugins/datask/composer/voceconnect/voce-post-expiration/voce-post-expiration.php on line 44`

### PR DESCRIPTION
**Pull request by kevinlangleyjr**
Fixes #2

### CODE REVIEW

File: voce-post-expiration.php [hunk 1]
```diff
@@ -40,8 +41,8 @@ public static function enqueue_admin_scripts() {
 		if ( !self::is_enabled() ) {
 			return;
 		}
-		// js to hide the Add New menu for this post type
-		wp_enqueue_script( 'post-expiration', plugins_url('js/voce-post-expiration.js', __FILE__), array( 'jquery' ), SCRIPT_VERSION, true );
+
+		wp_enqueue_script( 'post-expiration', plugins_url('js/voce-post-expiration.js', __FILE__), array( 'jquery' ), self::VERSION, true );
```
Comment (matgargano) [inline voce-post-expiration.php]: TAKE CHARGE @kevinlangleyjr  TAKE CHARGE BRO

**Comment by smccafferty** [comment]
Thanks! @kevinlangleyjr
